apiVersion: iam.aws.upbound.io/v1beta1
kind: User
metadata:
  annotations:
    crossplane.io/composition-resource-name: test-user
  generateName: example-
  labels:
    crossplane.io/composite: example
    dummy: foo
    testing.upbound.io/example-name: test-user
  name: test-user
  ownerReferences:
  - apiVersion: example.crossplane.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: XR
    name: example
    uid: ""
spec:
  forProvider: {}
